'use strict';

export const DD_ROOT_PATH: DirectoryPath = 'E:/Program Files (x86)/Steam/steamapps/common/DarkestDungeon';

export const SOURCES: SourcePath[] = [DD_ROOT_PATH];

export const ACTIVITY_LOG_PATH: DirectoryPath = 'activity_log';
export const AUDIO_PATH: DirectoryPath = 'audio';
export const CAMPAIGN_PATH: DirectoryPath = 'campaign';
export const COLOURS_PATH: DirectoryPath = 'colours';
export const CURIOUS_PATH: DirectoryPath = 'curious';
export const CURSORS_PATH: DirectoryPath = 'cursors';
export const DLC_PATH: DirectoryPath = 'dlc';
export const DUNGEONS_PATH: DirectoryPath = 'dungeons';
export const EFFECTS_PATH: DirectoryPath = 'effects';
export const FE_FLOW_PATH: DirectoryPath = 'fe_flow';
export const FONTS_PATH: DirectoryPath = 'fonts';
export const FX_PATH: DirectoryPath = 'fx';
export const GAME_OVER_PATH: DirectoryPath = 'game_over';
export const HEROES_PATH: DirectoryPath = 'heroes';
export const INVENTORY_PATH: DirectoryPath = 'inventory';
export const LOADING_SCREEN_PATH: DirectoryPath = 'loading_screen';
export const LOCALIZATION_PATH: DirectoryPath = 'localization';
export const LOOT_PATH: DirectoryPath = 'loot';
export const MAPS_PATH: DirectoryPath = 'maps';
export const MODES_PATH: DirectoryPath = 'modes';
export const MODS_PATH: DirectoryPath = 'mods';
export const MONSTERS_PATH: DirectoryPath = 'monsters';
export const OVERLAYS_PATH: DirectoryPath = 'overlays';
export const PANELS_PATH: DirectoryPath = 'panels';
export const PROPS_PATH: DirectoryPath = 'props';
export const RAID_PATH: DirectoryPath = 'raid';
export const RAID_RESULTS_PATH: DirectoryPath = 'raid_results';
export const SCRIPTS_PATH: DirectoryPath = 'scripts';
export const SCROLLS_PATH: DirectoryPath = 'scrolls';
export const SHADERS_PATH: DirectoryPath = 'shaders';
export const SHARED__PATH: DirectoryPath = 'shared';
export const SOUNDTRACK_PATH: DirectoryPath = 'soundtrack';
export const TRINKETS_PATH: DirectoryPath = 'trinkets';
export const UPGRADES_PATH: DirectoryPath = 'upgrades';
